"""End-to-end smoke test for folio generate."""

import pytest
from unittest.mock import patch, MagicMock
from pathlib import Path
from datetime import datetime, timezone
from typer.testing import CliRunner

from folio.cli import app
from folio.github import UserProfile, RepoData, StatsData, GitHubData

runner = CliRunner()


@pytest.fixture
def mock_github_data():
    return GitHubData(
        user=UserProfile(
            login="smoketest",
            name="Smoke Test",
            avatar_url="https://example.com/avatar.png",
            bio="Testing the pipeline",
            followers=10,
            following=5,
        ),
        repos=[
            RepoData(
                name="public-repo",
                full_name="smoketest/public-repo",
                description="A test repo",
                language="Python",
                stars=5,
                last_updated=datetime(2026, 3, 1, tzinfo=timezone.utc),
                is_fork=False,
                is_private=False,
                fork_parent=None,
                private_reason=None,
                html_url="https://github.com/smoketest/public-repo",
                readme_text="# Test\nA test repo.",
                recent_commits=["feat: add stuff"],
            ),
            RepoData(
                name="private-repo",
                full_name="smoketest/private-repo",
                description="Secret",
                language="Go",
                stars=0,
                last_updated=datetime(2026, 2, 1, tzinfo=timezone.utc),
                is_fork=False,
                is_private=True,
                fork_parent=None,
                private_reason="Under NDA",
                html_url="https://github.com/smoketest/private-repo",
            ),
        ],
        stats=StatsData(
            commits=100,
            pull_requests=8,
            issues=12,
            streak_days=21,
            stars_earned=5,
            languages={"Python": 60.0, "Go": 40.0},
        ),
    )


class TestSmoke:

    @patch("folio.cli.fetch_github_data")
    def test_generate_no_ai_writes_files(self, mock_fetch, mock_github_data, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)

        # Write config using absolute path to fixtures
        fixtures = Path(__file__).parent / "fixtures"
        config_path = tmp_path / ".profile.yml"
        config_path.write_text((fixtures / "sample_config.yml").read_text())

        mock_fetch.return_value = mock_github_data

        result = runner.invoke(app, ["generate", "--config", str(config_path), "--no-ai"])
        assert result.exit_code == 0, f"CLI failed: {result.output}"

        # Check README.md was written
        readme = tmp_path / "README.md"
        assert readme.exists(), "README.md not created"
        readme_text = readme.read_text()
        assert len(readme_text) > 0, "README.md is empty"
        assert "Generated by Folio" in readme_text

        # Check dist/ was created
        dist = tmp_path / "dist"
        assert dist.exists(), "dist/ not created"
        assert (dist / "index.html").exists(), "index.html not created"

        html = (dist / "index.html").read_text()
        assert "<!DOCTYPE html>" in html

    @patch("folio.cli.fetch_github_data")
    def test_private_repo_no_link_in_html(self, mock_fetch, mock_github_data, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        fixtures = Path(__file__).parent / "fixtures"
        config_path = tmp_path / ".profile.yml"
        config_path.write_text((fixtures / "sample_config.yml").read_text())
        mock_fetch.return_value = mock_github_data

        runner.invoke(app, ["generate", "--config", str(config_path), "--no-ai"])

        html = (tmp_path / "dist" / "index.html").read_text()
        assert "github.com/smoketest/private-repo" not in html
